# Deploy to Firebase Hosting on merge
name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY || 'AIzaSyBJmLC5ksvbQ26QpW04UeTMG3n0YQ5wjQg' }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN || 'budgetapp-254a2.firebaseapp.com' }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID || 'budgetapp-254a2' }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET || 'budgetapp-254a2.firebasestorage.app' }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID || '159607987904' }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID || '1:159607987904:web:a6996f58714c9e57635725' }}
      
      - name: Create Firebase service account key
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUDGETAPP_254A2 }}' > $HOME/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUDGETAPP_254A2 != '' }}
      
      - name: Deploy to Firebase Hosting
        run: |
          if [ -n "$FIREBASE_SERVICE_ACCOUNT" ]; then
            export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json
            npx firebase-tools deploy --only hosting --project budgetapp-254a2 --non-interactive
          else
            echo "⚠️  Firebase service account not configured. Skipping Firebase deployment."
            echo "Please set FIREBASE_SERVICE_ACCOUNT_BUDGETAPP_254A2 secret in repository settings."
          fi
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUDGETAPP_254A2 }}
      
      - name: Clean up
        run: |
          if [ -f "$HOME/firebase-service-account.json" ]; then
            rm $HOME/firebase-service-account.json
          fi
        if: always()
